# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    oauth2.resource_owner.name: openpp

services:
    oauth2.security.authentication.listener.api:
        class:  AppBundle\Security\Http\Firewall\OAuthApiListener
        arguments:
            -   @security.token_storage
            -   @security.authentication.manager
            -   @logger
            -   %oauth2.resource_owner.name%

    oauth2.security.request.verifytoken:
        class: AppBundle\OAuth\Request\VerifyToken
        arguments:
            -   @hwi_oauth.http_client
            -   @doctrine.orm.entity_manager
            -   %openpp_oauth_client.client_verify_url%

    oauth2.security.authentication.provider.api:
        class:  AppBundle\Security\Core\Authentication\Provider\OAuthApiProvider
        arguments:
            -   @hwi_oauth.user.provider.fosub_bridge
            -   @hwi_oauth.resource_ownermap.main
            -   @hwi_oauth.user_checker
            -   @oauth2.security.request.verifytoken

