hwi_oauth:
    # name of the firewall in which this bundle is active, this setting MUST be set
    firewall_name: main
    resource_owners:
            my_custom:
                type:                oauth2
                client_id:           <client_id>
                client_secret:       <client_secret>
                access_token_url:    https://path.to/oauth/v2/token
                authorization_url:   https://path.to/oauth/v2/authorize
                infos_url:           https://path.to/api/user
                scope:               "read"
                user_response_class: HWI\Bundle\OAuthBundle\OAuth\Response\PathUserResponse
                paths:
                    identifier: id
                    nickname:   username
                    realname:   fullname